### ISSUE TITLE
[SMTChecker] CHC engine throws `out_of_range` in a simple example with two libraries and an internal call

### ISSUE THREAD

**Issue by bshastry** [ethereum/solidity#13477]
```
pragma experimental SMTChecker;
library L1 {}
library L2 {
  function f1() public {}
  function f() internal { f1(); }
}
```

throws

https://github.com/ethereum/solidity/blob/51929652291a833889c2f3132b2ca6f037c02a56/libsolidity/formal/CHC.cpp#L1526

**Comment by xenide** [comment]
seems to happen for `bmc` as well. Is no one else having this issue?

**Comment by cameel** [comment]
@xenide How are you running it? I managed to reproduce for CHC without the pragma:

`test.sol`
```solidity
library L1 {}
library L2 {
    function f1() public {}
    function f() internal { f1(); }
}
```
```bash
solc test.sol --model-checker-engine chc
```
```
Uncaught exception:
Dynamic exception type: std::out_of_range
std::exception::what: map::at
```

But not with BMC:
```bash
solc test.sol --model-checker-engine bmc
```

By the way, this started happening in 0.8.4. It does not crash on earlier versions.

**Comment by xenide** [comment]
I'm using `foundry` with the following config: 

```toml
[profile.default.model_checker]
contracts = { "src/curve/stable/StablePair.sol" = [ "StablePair" ] }
engine = "chc"
timeout = 100000
targets = [
    "assert",
]
```

I'm just running it on one contract and it's an actual contract not a library. Do we know which index it was trying to access? It happens on both `0.8.13` and `0.8.17`. When I use `bmc` it also fails, but with an exit code 1. To see the actual run, see [this ](https://github.com/vexchange/v3-core/actions/runs/3357572784/jobs/5760953311)
