### ISSUE TITLE
Use the official CircleCI orb for shellcheck

### ISSUE THREAD

**Issue by davidcian** [ethereum/solidity#8801]
In the [CircleCI config file](https://github.com/ethereum/solidity/blob/develop/.circleci/config.yml), shellcheck is used as follows:
```
chk_coding_style:
    docker:
      - image: buildpack-deps:focal
    steps:
      - checkout
      - run:
          name: Install shellcheck
          command: apt -q update && apt install -y shellcheck
      - run:
          name: checking shell scripts
          command: ./scripts/chk_shellscripts/chk_shellscripts.sh
```
It would maybe be interesting to use the [official CircleCI shellcheck orb](https://circleci.com/orbs/registry/orb/circleci/shellcheck), especially since the command to install shellcheck is [failing atm](https://circleci.com/gh/ethereum/solidity/310227?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for some reason.

It would also be perhaps more easily maintainable to use the orb's interface instead of the `chk_shellscripts.sh`.
